# Generated by Django 3.2 on 2021-04-28 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Kategoria')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorii',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Imie Kobiety')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Treść artykułu')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Zdjęcie')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Czas utworzenia')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Ostatnia zmina')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publikacja')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='women.category', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Znane Kobiety',
                'verbose_name_plural': 'Znane Kobiety',
                'ordering': ['-time_create', 'title'],
            },
        ),
    ]
